package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Spak_fast'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Spak_fast")) {
    expectSteps {
        script {
            scriptContent = "timeout %sleep.time%"
        }
    }
    steps {
        insert(1) {
            gradle {
            }
        }
    }
}
