package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'SubProject_SubProject_Confff'
in the project with id = 'SubProject_SubProject', and delete the patch script.
*/
create(RelativeId("SubProject_SubProject"), BuildType({
    id("SubProject_SubProject_Confff")
    name = "Confff"
}))

