package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.BuildFeature
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'UnitTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("UnitTests")) {
    features {
        val feature1 = find<BuildFeature> {
            feature {
                type = "teamcity.stash.status"
                param("secure:stash_username", "zxx460d7c5f412e043eb885f5f29d4bb604a6d8b24ef741573d")
                param("stash_failCancelledBuilds", "true")
                param("stash_only_latest", "true")
                param("stash_username", "%env.STASH_USERNAME%")
                param("stash_vcsignorecsv", "mini_fabrics")
            }
        }
        feature1.apply {
            param("secure:stash_username", "credentialsJSON:e3d7212e-2b84-425b-b126-129ee41730a3")
        }
    }
}
