package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "OAuthProvider"
                id = "PROJECT_EXT_33"
                param("secure:aws.secret.access.key", "credentialsJSON:e047fca7-67ec-4df8-8485-ccebd33722f8")
                param("displayName", "Amazon ECR Connection")
                param("aws.access.key.id", "aaasdas")
                param("aws.credentials.type", "aws.access.keys")
                param("aws.region.name", "eu-west-1")
                param("registryId", "123412315")
                param("providerType", "AmazonDocker")
            }
        }
    }
}
