package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'CSubProject2'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("CSubProject2")) {
    check(name == "CSubProject #2") {
        "Unexpected name: '$name'"
    }
    name = "3sasdsadsa"
}
