package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'SubProject_SubProject'
in the project with id = 'SubProject', and delete the patch script.
*/
create(RelativeId("SubProject"), Project({
    id("SubProject_SubProject")
    name = "SubProject"
}))

