package DslTest.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.changeProject

/*
This patch script was generated by TeamCity on settings change in UI.
To apply it, change the project with uuid = '68ed399e-3cdc-4ffd-b638-e13a0b5b709f'
accordingly and delete the patch script.
*/
changeProject("68ed399e-3cdc-4ffd-b638-e13a0b5b709f") {
    features {
        add {
            dockerRegistry {
                id = "PROJECT_EXT_4"
                name = "Docker Registry - paksv"
                url = "https://docker.io"
                userName = "paksv"
                password = "credentialsJSON:ed7ae30f-c857-4ea3-b21c-804bf3868768"
            }
        }
    }
}
