package DslTest.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.projectFeatures.dockerRegistry
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.changeProject

/*
This patch script was generated by TeamCity on settings change in UI.
To apply it, change the project with uuid = '68ed399e-3cdc-4ffd-b638-e13a0b5b709f'
accordingly and delete the patch script.
*/
