package DslTest.patches.projects

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.Project
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.changeProject

/*
This patch script was generated by TeamCity on settings change in UI.
To apply it, change the project with uuid = '68ed399e-3cdc-4ffd-b638-e13a0b5b709f'
accordingly and delete the patch script.
*/
changeProject("68ed399e-3cdc-4ffd-b638-e13a0b5b709f") {
    features {
        add {
            feature {
                type = "JetBrains.SharedResources"
                id = "PROJECT_EXT_3"
                param("quota", "-1")
                param("name", "Res2")
                param("type", "quoted")
            }
        }
    }
}
