package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'AnotherRoot'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("AnotherRoot")
    name = "Another Root"
    url = "/Users/sergeypak/projects/Other/teamcity-dsl-settings/"
    authMethod = password {
        userName = "user"
        password = "credentialsJSON:6c7137b9-e299-4354-9e85-f450d1564c7d"
    }
}))

