package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2018_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'AnotherRoot'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("AnotherRoot")) {
    val expected = GitVcsRoot({
        id("AnotherRoot")
        name = "Another Root"
        url = "/Users/sergeypak/projects/Other/teamcity-dsl-settings/"
        authMethod = password {
            userName = "user"
            password = "%env.TOKEN%"
        }
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        authMethod = password {
            userName = "user"
            password = "credentialsJSON:d8414e5e-2443-48ad-9a7e-3804b6c84cf2"
        }
    }

}
