package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Template
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a template with id = 'TemplateWithPasswort'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Template({
    id("TemplateWithPasswort")
    name = "Template With Passwort"

    params {
        password("pwwd", "credentialsJSON:76bf027d-7b81-459d-8acd-81a5b4d432d0", label = "Pwd Label")
    }
}))

