package patches.templates

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'Ttt'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("Ttt")) {
    expectSteps {
        script {
            id = "RUNNER_31"
            scriptContent = "sleep 360"
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            id = "RUNNER_31"
            clearConditions()
            scriptContent = "#sleep 360"
        }
    }
}
