package DslTest.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.dockerBuild
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'Docker_Tester' (id = 'Docker_Tester')
accordingly and delete the patch script.
*/
changeBuildType("Docker_Tester") {
    expectSteps {
        step {
            name = "Docker Build"
            type = "Docker Build"
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("command.args", "--pull")
            param("docker.image.namesAndTags", "%image-name%:%teamcity.build.id%")
            param("dockerfile.path", "Dockerfile")
            param("dockerfile.source", "PATH")
        }
        script {
            name = "Tag & Push"
            scriptContent = """
                docker tag %image-name%:%teamcity.build.id% %username%/%image-name%:%teamcity.build.id%
                docker push %username%/%image-name%:%teamcity.build.id%
            """.trimIndent()
        }
    }
    steps {
        insert(0) {
            dockerBuild {
                name = "Docker Build"
                source = path {
                    path = "Dockerfile"
                }
                namesAndTags = "%image-name%:%teamcity.build.id%"
            }
        }
        items.removeAt(1)
    }
}
