package DslTest.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.DockerBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.dockerBuild
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with uuid = 'Docker_Tester' (id = 'Docker_Tester')
accordingly and delete the patch script.
*/
changeBuildType("Docker_Tester") {
    expectSteps {
        dockerBuild {
            name = "Docker Build"
            source = path {
                path = "Dockerfile"
            }
            namesAndTags = "%image-name%:%teamcity.build.id%"
        }
        script {
            name = "Tag & Push"
            scriptContent = """
                docker tag %image-name%:%teamcity.build.id% %username%/%image-name%:%teamcity.build.id%
                docker push %username%/%image-name%:%teamcity.build.id%
            """.trimIndent()
        }
    }
    steps {
        update<DockerBuildStep>(0) {
            source = path {
            }
            namesAndTags = "%username%/%image-name%:%teamcity.build.id%"
        }
    }
}
