package DslTest.patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2017_2.*
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2017_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2017_2.ui.changeBuildType

/*
This patch script was generated by TeamCity on settings change in UI.
To apply it, change the buildType with uuid = 'Temporary'
accordingly and delete the patch script.
*/
changeBuildType("Temporary") {
    expectSteps {
        maven {
            mavenVersion = custom {
            }
            dockerImage = "openjdk/8-jdk"
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            mavenVersion = defaultProvidedVersion()
            dockerPull = true
        }
    }
}
